ALTER TABLE users
    ADD COLUMN name VARCHAR(100) NOT NULL DEFAULT 'Unknown';
ALTER TABLE users
    ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT now();
ALTER TABLE users
    DROP COLUMN IF EXISTS role;
